version: '2'
services:
  nginx:
    container_name: nginx
    build: ./nginx

    env_file: .env

    environment:
      SHELF_HOST: "shelf.${HOST}"
    
    ports:
      - "80:80"

    volumes:
      - "shelf_public:/srv/shelf_public:ro"

    depends_on:
      - shelf

    command: ./run.sh

  db:
    container_name: db
    image: mysql:5.6

    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    ports:
      - 3306:3306

    volumes:
      - db:/var/lib/mysql

  shelf:
    container_name: shelf
    build: ./shelf

    env_file: .env

    environment:
      DB_HOST: db
      RAILS_LOG_TO_STDOUT: 1

    ports:
      - 3000:3000

    volumes:
      - shelf_public:/app/public

    depends_on:
      - db

volumes:
  db:
  shelf_public:
