version: '2'
services:
  consul:
    container_name: consul
    image: consul:1.0.0

    command: "consul agent -server -client 0.0.0.0 -bootstrap -data-dir=/consul/data -ui"

    ports:
      - 8500:8500

    volumes:
      - "consul:/consul/data"

  registrator:
    container_name: registrator
    image: gliderlabs/registrator

    command: "consul://consul:8500"

    depends_on:
      - consul

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  nginx:
    container_name: nginx
    build: ./nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/srv/main:/srv/main:ro"
      - "/srv/images:/srv/images:ro"
      - "shelf2_public:/srv/shelf2_public:ro"
      - "/cert:/cert:ro"

    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx

    links:
      - fluentd

    depends_on:
      - consul
      - shelf2-frontend
      - homepage

    command: "envconsul -consul-addr consul:8500 -prefix hosting -upcase ./run.sh"

  db:
    container_name: db
    build: ./db

    ports:
      - 3306:3306

    volumes:
      - db:/var/lib/mysql

    command: "envconsul -consul-addr consul:8500 -prefix database -upcase docker-entrypoint.sh mysqld"

    depends_on:
      - consul

  shelf2-backend:
    container_name: shelf2
    image: quay.io/sirech/shelf2-backend

    ports:
      - 3000:3000

    command: "rails s -b 0.0.0.0"

    depends_on:
      - consul
      - db

  shelf2-frontend:
    container_name: shelf2-frontend
    image: quay.io/sirech/shelf2-frontend

    volumes:
      - shelf2_public:/app/public

    depends_on:
      - shelf2-backend

  homepage:
    container_name: homepage
    image: quay.io/sirech/homepage

    volumes:
      - "/srv/main:/app/public"

  fluentd:
    container_name: fluentd
    build: ./fluentd

    links:
      - elasticsearch

    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch

    expose:
      - 9200

    ports:
      - 9200:9200

    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"

  kibana:
    container_name: kibana
    image: kibana

    links:
      - elasticsearch

    ports:
      - 5601:5601

volumes:
  db:
  shelf2_public:
  consul:
