version: '3'
services:

  nginx:
    container_name: nginx
    build: ./nginx

    env_file: .env

    environment:
      SHELF2_HOST: "shelf2.${HOST}"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/srv/main:/srv/main:ro"
      - "/srv/images:/srv/images:ro"
      - "/srv/shelf2_public:/srv/shelf2_public:ro"
      - "/cert:/cert:ro"

    networks:
      - backend
      - web

    command: ./run.sh

  db:
    container_name: db
    image: mysql:5.7

    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    ports:
      - 3306:3306

    networks:
      - backend

    volumes:
      - db:/var/lib/mysql

  shelf2-backend:
    container_name: shelf2
    image: quay.io/sirech/shelf2-backend

    env_file: .env

    environment:
      DB_HOST: db
      RAILS_LOG_TO_STDOUT: 1

    ports:
      - 3000:3000

    command: "rails s -b 0.0.0.0"

    networks:
      - backend
      - web

    depends_on:
      - db

networks:
  backend:
  web:

volumes:
  db:
