version: '3'
services:

  nginx:
    container_name: nginx
    build: ./nginx

    env_file: .env

    environment:
      SHELF2_HOST: "shelf2.${HOST}"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/srv/main:/srv/main:ro"
      - "/srv/images:/srv/images:ro"
      - "/srv/shelf2_public:/srv/shelf2_public:ro"
      - "/cert:/cert:ro"

    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"

    links:
      - fluentd

    depends_on:
      - shelf2-frontend
      - homepage

    command: ./run.sh

  db:
    container_name: db
    image: mysql:8.0.11

    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

    ports:
      - 3306:3306

    volumes:
      - db:/var/lib/mysql

  shelf2-backend:
    container_name: shelf2
    image: quay.io/sirech/shelf2-backend

    env_file: .env

    environment:
      DB_HOST: db
      RAILS_LOG_TO_STDOUT: 1

    ports:
      - 3000:3000

    command: "rails s -b 0.0.0.0"

    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"

    links:
      - fluentd

    depends_on:
      - db

  shelf2-frontend:
    container_name: shelf2-frontend
    image: quay.io/sirech/shelf2-frontend

    volumes:
      - /srv/shelf2_public:/app/public

    depends_on:
      - shelf2-backend

  homepage:
    container_name: homepage
    image: quay.io/sirech/homepage2

    volumes:
      - "/srv/main:/app/public"

  fluentd:
    container_name: fluentd
    build: ./fluentd

    links:
      - elasticsearch

    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch

    expose:
      - 9200

    ports:
      - 9200:9200

    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"

  kibana:
    container_name: kibana
    image: kibana

    links:
      - elasticsearch

    ports:
      - 5601:5601

volumes:
  db:
